spring.application.name=intershop

spring.datasource.url=jdbc:postgresql://localhost:5432/intershop
spring.datasource.username=postgres
spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver


#spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE


#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect