spring.application.name=intershop

#spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.r2dbc.username=sa
#spring.r2dbc.password=

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/intershop
spring.r2dbc.username=postgres
spring.r2dbc.password=admin

items.path=showcase/items
image.path=showcase/images

#spring.data.redis.host=127.0.0.1
spring.data.redis.host=${SPRING_REDIS_HOST:127.0.0.1}
spring.data.redis.port=6379

services.api.base-url=http://localhost:8081

spring.security.oauth2.client.registration.keycloak.provider=keycloak

spring.security.oauth2.client.registration.keycloak.client-id=yandex-test
spring.security.oauth2.client.registration.keycloak.client-secret=c9bd5Rr5K1Jcxw8qFrPcBqulqBcJfwgw
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8080/login/oauth2/code/keycloak

#provider: keycloak
#authorization-grant-type: client_credentials
#client-id: ${KEYCLOAK_CLIENT_ID:intershop}
#client-secret: ${KEYCLOAK_CLIENT_SECRET:HBpBcSUPAiYmJM1yPQgxynn6m9j0AEHt}
#scope: profile
#client-authentication-method: client_secret_post

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8082/realms/master