openapi: 3.0.3
info:
  title: Сервис платежей
  version: 1.0.0
paths:
  /balance:
    get:
      tags:
        - payment
      summary: Получение баланса на счёте по userId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  format: int64
                  example: 123
      responses:
        '200':
          description: Балланс
          content:
            application/json:
              schema:
                type: number
                format: double
                example: 1234.56
  /pay:
    put:
      tags:
        - payment
      summary: Осуществление платежа по userId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: double
                  example: 1234.56
                  description: Сумма платежа
                userId:
                  type: integer
                  format: int64
                  example: 123456789
                  description: Идентификатор пользователя
              required:
                - amount
                - userId
      responses:
        '200':
          description: Оплата успешно выполнена
        '402':
          description: Недостаточно средств
