server.port=8081

#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html

spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER_URI:http://localhost:8082/realms/intershop}
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/intershop