server.port=8081

#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/master